name: SDRangel Mac release build

on:
  push:
    branches:
      - mac_ci
    tags:
      - 'v*'

jobs:
  build_mac_arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Update brew
        run: brew update
      - name: Install brew packages
        run: brew install nasm subversion
      - name: Install python packages for UHD
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install numpy mako requests Cheetah3 setuptools
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          host: 'mac'
          arch: 'clang_64'
          modules: 'qtcharts qtscxml qt5compat qtlocation qtmultimedia qtpositioning qtserialport qtspeech qtwebsockets qtwebengine qtshadertools qtwebchannel'
      - name: Configure SDRangel
        run: |
          source .venv/bin/activate
          mkdir build && cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_QT6=ON -DCMAKE_BUILD_TYPE=Release -DDEBUG_OUTPUT=ON -DENABLE_CHANNELRX_DEMODDATV=OFF -DENABLE_CHANNELTX_MODDATV=OFF -DENABLE_MIRISDR=OFF -DBUILD_SERVER=OFF -DENABLE_EXTERNAL_LIBRARIES=ON -DBUNDLE=ON -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=TRUE -DPYTHON_EXECUTABLE=`pwd`/.venv/bin/python3
      - name: Build SDRangel on Mac
        run: |
          source .venv/bin/activate
          cd build
          make -j3 all
      - name: Build dmg
        run: |
          cd build
          make package
      - name: Get version
        id: get_version
        run: echo "version=$(echo ${{github.ref_name}} | cut -c2-)" >> $env:GITHUB_OUTPUT
      - name: Get filename
        id: get_filename
        run: echo "filename=$(grep CPACK_PACKAGE_FILE_NAME build/CMakeCache.txt | cut -d "=" -f2)" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdrangel-${{ steps.get_version.outputs.version }}-macarm.dmg
          path: ${{ github.workspace }}/build/${{ steps.get_filename.outputs.filename }}.dmg
